test/shared/index.js

atpl added additional `fs.readFile` and `fs.readFileSync` calls when not caching.
Updating tests to account for the atpl changing.

fixing tests for atpl updates

---

Readme.md

The original dustjs has been unmaintained for years now. LinkedIn maintains a fork that is presently maintained, and it works with consolidate.

Added dustjs-linkedin to list of engines supported.

---

Readme.md
lib/consolidate.js
test/consolidate.js
test/fixtures/nunjucks/filters.nunjucks
test/shared/index.js

* exposes `requires`, and thus engine instances
* added basic tests for those
* added nunjucks filters test
This allows developers to access the engine instance itself, e.g.
```js
var cons = require('consolidate'),
nunjucks = require('nunjucks');
cons.requires.nunjucks.addFilter('foo', function () {
return 'bar';
});
```

expose 'requires' object

---

lib/consolidate.js
package.json
test/shared/index.js
test/shared/react.js

If no callback `fn` is provided, render functions should return Promises which either resolve to the compiled HTML or an error.
No changes are made to the regular API, only the addition of the return value when no callback is provided.

Add support for Promises

---

Readme.md

The current example should show `nunjucks.configure()`, since that's how to create a new nunjucks env.

docs update for requires

---

lib/consolidate.js
test/shared/index.js

It's clear from the existing tests that the different keys were intentional, but there are a couple of good reasons to normalize them:
1. It makes it a lot easier to automate the process of pre-loading an engine into the requires object (you don't have to keep track of the alternate key names)
2. The current scheme is not consistent--Liquid loads the "tinyliquid" engine but uses "requires.liquid", and Hogan loads the "hogan.js" engine but uses "requires.hogan"

Normalize keys in "requires" object

---

lib/consolidate.js
test/consolidate.js
test/fixtures/nunjucks/_base_layout.nunjucks
test/fixtures/nunjucks/include.nunjucks
test/fixtures/nunjucks/layouts.nunjucks
test/shared/includes.js

Nunjucks extends doesn't work properly without #152. Its conflicted and not updated for so long time and i really like nunjucks with consolidate so here is updated version of @aroman pull request.

Pass express 'views' setting to nunjucks

---

Readme.md

http://documentcloud.github.io/underscore/ become 404, so use http://underscorejs.org/#template

update underscore website url

---

lib/consolidate.js

Not every `require` implementation has `require.extensions` (specifically browserify doesn't).

Don't fatal if `require.extensions` doesn't exist

---

Readme.md

I am a collaborator at EJS.
EJS v2+ is developed at https://github.com/mde/ejs. We also now have a website: http://ejs.co/.
This PR updates the links for EJS.

Update ejs info

---

Readme.md

SWIG appears to be unmaintained, and the link to the website returns 404.

Mark SWIG as unmaintained in the README

---

Readme.md
lib/consolidate.js
package.json
test/consolidate.js
test/fixtures/teacup/user.teacup

Descendant of coffeecup, requested in #103.
Disabling caching currently won't work for [helpers](https://github.com/goodeggs/teacup#helpers) since they use the Node require cache.  I could diff and purge the whole `module.cache` after each render, but that feels janky.  Better to just use node-supervisor and friends in development.

Support Teacup

---

lib/consolidate.js

I noticed that clearCache only clears half the cache.  It turns out that the readCache is burning me when I'm trying to clear the cache in consolidate.

Clear the entire cache

---

lib/consolidate.js
package.json

Marko changed its implementation and thus "The render callback will no longer receive a string in Marko v4. Use `renderToString(data, callback)` instead" See https://github.com/marko-js/marko/pull/450.
This change is compatible with the current stable public version.

Improve Marko Implementation (support v4 & handle cached templates)

---

lib/consolidate.js
test/consolidate.js
test/fixtures/dust/user_template_name.dust
test/shared/dust.js

This will ensure when context.getTemplateName is called in a base template the appropriate name is available.
Docs for dust helper API can be found here: http://www.dustjs.com/docs/helper-api/

Passing in template name to dust compile.

---

test/fixtures/react/user.react

React emitted this deprecation warning while running the tests: 
> Warning: Accessing `createClass` via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
I replaced `React.createClass` with a plain javascript class in the fixture to future-proof your tests.

Fix React deprecation warning in test

---

lib/consolidate.js
test/consolidate.js
test/fixtures/underscore/partials.underscore
test/fixtures/underscore/user_partial.underscore
test/shared/partials.js

Made a small quick modification to the underscore support render method to allow the template partials to get compiled allowing data to get passed to those as well. 
var user = {username: 'Beetlejuice'};
<%= partials.xanadu(user) %>
Ya dig?

Partials Underscore Compile

---

lib/consolidate.js

Twig allows to include partials. Unfortunately this is possible at the moment when using `consolidate`, since it doesn't pass the options `allowInlineIncludes` and `path` to `twig.js`.

Use `allowInlineIncludes` and `path` option for twig engine

---

Readme.md

Velocity.js support was added in https://github.com/tj/consolidate.js/commit/e223a27d6b83e91bfae1c9f5497e45549eecd1b4, but wasn't included in the readme.

Add velocityjs to readme.

---

Readme.md

Remove 3.X and add "Supported Express version" section.

Improve documentation about Express version

---

Readme.md

When the list of template engines in the README was converted to a table, Squirrelly (which had just been added) was accidentally left off. See issue #322
Thanks!

Re-add Squirrelly to supported template engines list

---

lib/consolidate.js
package.json

Use `mustache.render()` instead of `mustache.to_html()` that got removed as of `mustache` v4 (https://github.com/janl/mustache.js/pull/735).
This closes #331

Fix mustache support

---

lib/consolidate.js

Hey!
At the moment, using namespaces with `twig.js` is not possible, because the option `namespaces` is not passed to the render function.
See also: https://github.com/twigjs/twig.js/wiki#namespaces

Use `namespaces` option for twig engine

---

package.json

**What's the problem this PR addresses?**
`consolidate` has some undeclared optional peer dependencies causing it to rely on hoisting to be in its favour which is not guaranteed.
https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
**How did you fix it?**
Add all undeclared dependencies as optional peer dependencies, using the ranges from `devDependencies`

fix: add undeclared optional peer dependencies

---

lib/consolidate.js

Hello,
we are in a situation where we have .dust file in two different location.
So we set on express 2 different views folder like this: app.set('views', [folder1, folder2]);
But Dustjs is not enable to check correctly in both folder with partials ( {>myFile.dust} )
The array of folder is stringify and dust js throw an error.
The objectif is to handle the case that there is multiple views folder and manage to find the file correctly.
Btw if the file is in both directory I added a warning and the first file found is used by default.

Handle multiple views folder for dustjs partials

---

lib/consolidate.js

This PR does two things.
First allows twigs to include other twigs by using the TwingFilesystemLoader if options.settings.views is present and valid.  
Second fixes #329 by allowing a pre-setup TwingEnvironment to get passed in through consolidate's requires.twing

Fixed issues with twing support
